### ISSUE TITLE
Roboto font loaded over plaintext HTTP

### ISSUE THREAD

**Issue by rec0de** [yadakhov/torelay#1]
Hi!

I just looked trough your code and noticed that the Roboto Webfont is loaded over plaintext HTTP even if the main connection is TLS encrypted.
This causes a 'mixed content' warning in Firefox (and perhaps Chrome?)

Additionaly I would suggest enabling HSTS headers to prevent downgrading attacks.

Thanks for creating this :)

-- rec0de

**Comment by rec0de** [comment]
Fixed apparently.

**Comment by yadakhov** [comment]
Yup.  fixed.  The torelay.com wasn't under https at first.
