### ISSUE TITLE
User agent randomization

### ISSUE THREAD

**Issue by rec0de** [yadakhov/torelay#2]
Hi!

It looks like you use a certain set of user agents to obscure the fact that the data is coming from torelay.com instead of a regular client. As of my understanding of the TOR network it would be better to send the user agent of the latest TOR Browser Bundle ("Mozilla/5.0 (Windows NT 6.1; rv:31.0) Gecko/20100101 Firefox/31.0"), which is used by _all_ TOR Browser instances on all platforms to make the torelay.com traffic more difficult to differentiate from regular TOR traffic.

--rec0de

**Comment by yadakhov** [comment]
I wasn't aware TOR had a default user agent.  I'll code it in.
