### ISSUE TITLE
User Agent / HTTP Header not sent properly

### ISSUE THREAD

**Issue by rec0de** [yadakhov/torelay#4]
Hi!

It looks like your use of 'CURLOPT_HTTPHEADER' is incorrect as you only set the Useragent, not the entire header. Viewing ipnumber.info trough torelay shows that an empty user agent is sent.
If you want to send header values you have to prefix them with the name of the value you want to change (see http://curl.haxx.se/libcurl/c/CURLOPT_HTTPHEADER.html).
As you are only sending the user agent for now, I would suggest replacing 'CURLOPT_HTTPHEADER' with 'CURLOPT_USERAGENT'.

--rec0de

**Comment by yadakhov** [comment]
I'll check it out later today.  I'm think for rewritting the curl logic to use Guzzle package.
